Alias /awstatsclasses /opt/awstats/wwwroot/classes
Alias /awstatscss /opt/awstats/wwwroot/css
Alias /awstatsicons /opt/awstats/wwwroot/icon
ScriptAlias /awstats/ /opt/awstats/wwwroot/cgi-bin/

<Directory /opt/awstats/wwwroot>
    Options +ExecCGI
    AllowOverride None
    Require all granted
</Directory>
