Include "/opt/awstats/wwwroot/cgi-bin/awstats.model.conf"

LogFile="/opt/awstats/deployment/access.log"
LogFormat=1
SiteDomain="analytics.example.test"
HostAliases="analytics.example.test localhost 127.0.0.1"
DNSLookup=0
DirData="/var/lib/awstats"
DirCgi="/awstats"
DirIcons="/awstatsicons"
DirLang="/opt/awstats/wwwroot/cgi-bin/lang"
AllowToUpdateStatsFromBrowser=0
CreateDirDataIfNotExists=1
